# /k8s/api-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  # The key is the environment variable name
  # The value is the base64-encoded version of our password 'supersecret'
  POSTGRES_PASSWORD: "c3VwZXJzZWNyZXQ="
